var mongoose = require('mongoose');
var Schema = mongoose.Schema;

//creating a schema
var questionSchema = new Schema({
    question: String,
    category: String,
    difficulty: String,
    questonBank: String,
    options: [String, String, String, String],
    answer: String
},{autoCreate: true});
//use Schema.add method to add keys/columns later
//REPLACE string with images and BLOBs


//Attach find Q by category helper query method to the question schema so that we can fetch easy, mod, hard easily:
questionSchema.query.byDifficulty = function(diff) {
    return this.where({ difficulty: diff });
  };
  questionSchema.query.byQuestion = function(qString) {
    return this.where({ question: qString });
  };

//create model from schema: schema-first approach
var Question = mongoose.model('Question', questionSchema);

console.log(Question);
//create collection forcefully
// Question.init().then(function(collection) {
//   console.log('Collection is created!');
// });
// console.log("i'm here");

var qE=new Question({
  question: "String",
  category: "String",
  difficulty: "easy",
  questonBank: "String",
  options: ["String", "String", "String", "String"],
  answer: "String"
});
var qM=new Question({
  question: "String",
  category: "String",
  difficulty: "moderate",
  questonBank: "String",
  options: ["String", "String", "String", "String"],
  answer: "String"
});
// var qD=new Question({
//   question: "String",
//   category: "String",
//   difficulty: "difficult",
//   questonBank: "String",
//   options: ["String", "String", "String", "String"],
//   answer: "String"
// });
try{
let saved = Question.create(qE);
let saved2 = Question.create(qM); 
//let saved3 = Question.create(qD);//when fail its goes to catch
console.log(saved); //when success it print.
console.log('after save');
} catch (err) {
console.log('err' + err);
}


// Question.create(que,function(err,doc){
//   console.log("in function"); 
// if (!err) 
// console.log(doc);
// else
// console.log(err);});

// que.save((err, doc) => {
//   if (!err) { console.log("succeeded:"+doc); }
//   else { console.log('Error in Question Save :' + err); }
// });

//que.save();

console.log('reached the end');
console.log(qE);
console.log(qM);
module.exports = { Question:Question };






//The _id will be autogenerated for each model made from the schema.
//https://mongoosejs.com/docs/api.html#schema_Schema-add iterate and more API
